# Generated by Django 3.2.19 on 2023-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Servicio')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Servicio')),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
